### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble-takedown#2]
@kevzawacki - hoping you can provide some copywriting support for this page: http://mozilla.github.io/thimble-takedown/

Turns out the second paragraph is not quite accurate. Does the following make sense to you? Do you think it would lead to any user confusion? Any edits you'd suggest?

"Projects you've published with the old Thimble will still be available at the same url they always were. However, you won't be able to make any updates to them, and they won't be remixable by others. You can easily re-publish your projects on the new Thimble, though. Sign in on thimble.mozilla.org and click Your Projects in the dropdown menu to find and re-publish your older projects."

also cc'ing @kgorr because I suspect you might get some questions about this after we officially retire old Thimble.

**Comment by hannahkane** [comment]
cc @cadecairos

**Comment by KGorr** [comment]
Thanks for keeping me in the loop, @hannahkane!

**Comment by KevZawacki** [comment]
@hannahkane Happy to help! My suggested edits (minor) to your proposed paragraph:

Projects you've published with the old Thimble will still be available at the same url they always were. However, these projects will be static: You won't be able to make updates, and they won't be remixable. 

But don't fret! You can easily re-publish your old projects on the new Thimble. Sign in on thimble.mozilla.org and click "Your Projects" in the dropdown menu to find and re-publish your old projects.

**Comment by hannahkane** [comment]
thanks, @KevZawacki. Great edits, as per usual. :)
